language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE IMAGER;" -U postgres

env:
  - DB_NAME=imager DB_USER=postgres DB_HOST='localhost' SECRET_KEY='el$_axvj9ph61uj0i_&c(*#1@l&t3hkd@z5h4ym&2u6x9tz(_u'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python django_imager/manage.py migrate easy_thumbnails
  - python django_imager/manage.py migrate
  - coverage run django_imager/manage.py test django_imager

after_success:
  - coveralls

notifications:
  email: false